-- Private manual workspace. Apply with scripts/workspace_postgres.py using
-- migration-owner credentials; the application role has no DDL privileges.
CREATE SCHEMA IF NOT EXISTS outreached_workspace;
REVOKE ALL ON SCHEMA outreached_workspace FROM PUBLIC;

CREATE TABLE IF NOT EXISTS outreached_workspace.schema_version (
    id INTEGER PRIMARY KEY CHECK (id = 1), version INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS outreached_workspace.profile (
    id INTEGER PRIMARY KEY CHECK (id = 1), data TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS outreached_workspace.leads (
    id TEXT PRIMARY KEY, company_name TEXT NOT NULL, siren TEXT NOT NULL DEFAULT '',
    contact_name TEXT NOT NULL DEFAULT '', email TEXT NOT NULL DEFAULT '',
    website TEXT NOT NULL DEFAULT '', city TEXT NOT NULL DEFAULT '',
    activity TEXT NOT NULL DEFAULT '', source TEXT NOT NULL DEFAULT '',
    notes TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'new',
    qualified BOOLEAN NOT NULL DEFAULT FALSE, created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS lead_email ON outreached_workspace.leads(email) WHERE email <> '';
CREATE UNIQUE INDEX IF NOT EXISTS lead_siren ON outreached_workspace.leads(siren) WHERE siren <> '';
CREATE TABLE IF NOT EXISTS outreached_workspace.suppressions (
    email TEXT PRIMARY KEY, created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS outreached_workspace.campaigns (
    id TEXT PRIMARY KEY, name TEXT NOT NULL, profile TEXT NOT NULL, created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS outreached_workspace.drafts (
    id TEXT PRIMARY KEY,
    campaign_id TEXT NOT NULL REFERENCES outreached_workspace.campaigns(id),
    lead_id TEXT NOT NULL REFERENCES outreached_workspace.leads(id) ON DELETE CASCADE,
    step INTEGER NOT NULL, subject TEXT NOT NULL, body TEXT NOT NULL,
    footer TEXT NOT NULL, sent_at TEXT, UNIQUE(lead_id, step)
);
CREATE TABLE IF NOT EXISTS outreached_workspace.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id TEXT NOT NULL REFERENCES outreached_workspace.leads(id) ON DELETE CASCADE,
    kind TEXT NOT NULL, detail TEXT NOT NULL, created_at TEXT NOT NULL
);
INSERT INTO outreached_workspace.schema_version(id,version) VALUES (1,1)
ON CONFLICT(id) DO NOTHING;
