#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
for dependency in uv pnpm node; do
  if ! command -v "$dependency" >/dev/null; then
    echo "Installez $dependency avant de lancer Lexia. Consultez README.md."
    exit 1
  fi
done
if [[ ! -f .runtime/auth/frontend.env ]]; then
  node frontend/scripts/setup-auth.mjs --output .runtime/auth --user admin \
    --origin http://localhost:3000 --backend-url http://127.0.0.1:8001
fi
# This file is generated by setup-auth, kept private and excluded from Git.
set -a
source .runtime/auth/frontend.env
set +a
export APP_ENV=development DEBUG=false COMMERCIAL_LAUNCH_ENABLED=false
export ALLOWED_HOSTS='["localhost","127.0.0.1"]'
export ALLOWED_ORIGINS='["http://localhost:3000"]'
export WORKSPACE_DB_PATH="${WORKSPACE_DB_PATH:-$PWD/backend/lexia.db}"
if [[ ! -d .venv || ! -d frontend/node_modules ]]; then
  echo "Installez les dépendances : uv sync --group dev && pnpm --dir frontend install --frozen-lockfile"
  exit 1
fi
for port in 8001 3000; do
  if lsof -nP -iTCP:"$port" -sTCP:LISTEN >/dev/null 2>&1; then
    echo "Le port $port est déjà utilisé. Fermez l’instance existante avant de relancer Lexia."
    exit 1
  fi
done
uv run uvicorn backend.app.main:app --host 127.0.0.1 --port 8001 &
lexia_backend_pid=$!
lexia_frontend_pid=""
cleanup() {
  kill "$lexia_backend_pid" 2>/dev/null || true
  if [[ -n "$lexia_frontend_pid" ]]; then kill "$lexia_frontend_pid" 2>/dev/null || true; fi
}
trap cleanup EXIT
trap 'exit 0' INT TERM
for attempt in {1..30}; do
  if curl -fsS http://127.0.0.1:8001/health >/dev/null 2>&1; then break; fi
  if ! kill -0 "$lexia_backend_pid" 2>/dev/null; then echo "Le serveur n’a pas démarré."; exit 1; fi
  sleep 0.5
done
curl -fsS http://127.0.0.1:8001/health >/dev/null
pnpm --dir frontend dev --hostname 127.0.0.1 --port 3000 &
lexia_frontend_pid=$!
echo "Lexia : http://localhost:3000/campaign — Ctrl+C pour arrêter."
echo "Identifiants privés : $PWD/.runtime/auth/workspace-login.txt"
while kill -0 "$lexia_backend_pid" 2>/dev/null && kill -0 "$lexia_frontend_pid" 2>/dev/null; do
  sleep 1
done
echo "Un serveur s’est arrêté. Consultez le message ci-dessus."
exit 1
